clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  build:
    image: gcr.io/time-coin/sbt:latest
    volumes:
      - /var/lib/sbt-cache:/workdir/sbt
      - /var/lib/ivy-cache:/workdir/ivy
    commands:
      - export SBTCMD='sbt -Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy/ -Divy.home=/workdir/ivy/'
      - cd /workdir/code && $SBTCMD stage
  build-installer:
    image: gcr.io/time-coin/wix-builder:0.1
    commands:
      - cp -rf /workdir/code/win-installer /home/wix/
      - cp -rf /workdir/code/target/universal/stage /home/wix/win-installer/
      - cd /home/wix/win-installer && bash build.sh
  github_release:
    image: plugins/github-release
    files:
      - /home/wix/win-installer/*.msi
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
