clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  build:
    image: gcr.io/time-coin/builder-java-sbt:0.1
    commands:
      - cd /workdir/code && sbt -Dsbt.global.base=/workdir/sbt/ -Dsbt.ivy.home=/workdir/ivy2/ -Divy.home=/workdir/ivy2/ publishLocal
  test:
    image: gcr.io/time-coin/sbt:latest
    commands:
      - ls /workdir/sbt/
      - ls /workdir/ivy2/
#  github_release:
#    image: plugins/github-release
#    files: /workdir/code/*.tgz
#    files: /workdir/code/*.zip
#    secrets: [ GITHUB_RELEASE_API_KEY ]
#    when:
#      event: tag
